### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by Brenex** [ShoGinn/RewardsBot#4]
I get this error intermittently. The last time it occurred was after it was running nicely for 10 minutes:

chrome_1        | 14:51:37.571 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/url (handler: ServicedSession)
chrome_1        | 14:51:37.572 INFO - To upstream: {"url": "https://www.bing.com", "sessionId": "dcb5c15a3944c9cd90d69c6d16587307"}
chrome_1        | 14:51:37.952 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":null}
chrome_1        | 14:51:37.957 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:37.960 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element (handler: ServicedSession)
chrome_1        | 14:51:37.961 INFO - To upstream: {"using": "xpath", "sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "value": ".//*[@id='sb_form_q']"}
chrome_1        | 14:51:37.977 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":{"ELEMENT":"0.43289581787061127-1"}}
chrome_1        | 14:51:37.980 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:37.980 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing GET on /session/dcb5c15a3944c9cd90d69c6d16587307/element/0.43289581787061127-1/displayed (handler: ServicedSession)
chrome_1        | 14:51:38.008 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":true}
chrome_1        | 14:51:38.011 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:38.011 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing GET on /session/dcb5c15a3944c9cd90d69c6d16587307/element/0.43289581787061127-1/enabled (handler: ServicedSession)
chrome_1        | 14:51:38.022 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":true}
chrome_1        | 14:51:38.025 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:38.025 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element (handler: ServicedSession)
chrome_1        | 14:51:38.026 INFO - To upstream: {"using": "xpath", "sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "value": ".//*[@id='sb_form_q']"}
chrome_1        | 14:51:38.051 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":{"ELEMENT":"0.43289581787061127-1"}}
chrome_1        | 14:51:38.056 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:38.057 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element/0.43289581787061127-1/clear (handler: ServicedSession)
chrome_1        | 14:51:38.057 INFO - To upstream: {"sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "id": "0.43289581787061127-1"}
chrome_1        | 14:51:38.088 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":null}
chrome_1        | 14:51:38.093 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:38.096 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element (handler: ServicedSession)
chrome_1        | 14:51:38.096 INFO - To upstream: {"using": "xpath", "sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "value": ".//*[@id='sb_form_q']"}
chrome_1        | 14:51:38.127 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":{"ELEMENT":"0.43289581787061127-1"}}
chrome_1        | 14:51:38.131 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:38.133 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element/0.43289581787061127-1/value (handler: ServicedSession)
chrome_1        | 14:51:38.133 INFO - To upstream: {"text": "university of puerto rico--aguadilla", "sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "id": "0.43289581787061127-1", "value": ["u", "n", "i", "v", "e", "r", "s", "i", "t", "y", " ", "o", "f", " ", "p", "u", "e", "r", "t", "o", " ", "r", "i", "c", "o", "-", "-", "a", "g", "u", "a", "d", "i", "l", "l", "a"]}
chrome_1        | 14:51:38.319 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":null}
chrome_1        | 14:51:39.323 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:39.327 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element/0.43289581787061127-1/submit (handler: ServicedSession)
chrome_1        | 14:51:39.331 INFO - To upstream: {"sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "id": "0.43289581787061127-1"}
chrome_1        | 14:51:39.975 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":null}
chrome_1        | 14:51:47.990 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:47.991 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element (handler: ServicedSession)
chrome_1        | 14:51:47.997 INFO - To upstream: {"using": "xpath", "sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "value": ".//*[@id='sb_form_q']"}
chrome_1        | 14:51:48.019 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":{"ELEMENT":"0.4794584323689508-1"}}
chrome_1        | 14:51:48.022 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
chrome_1        | 14:51:48.023 INFO - Handler thread for session dcb5c15a3944c9cd90d69c6d16587307 (chrome): Executing POST on /session/dcb5c15a3944c9cd90d69c6d16587307/element/0.4794584323689508-1/clear (handler: ServicedSession)
chrome_1        | 14:51:48.025 INFO - To upstream: {"sessionId": "dcb5c15a3944c9cd90d69c6d16587307", "id": "0.4794584323689508-1"}
chrome_1        | 14:51:48.051 INFO - To downstream: {"sessionId":"dcb5c15a3944c9cd90d69c6d16587307","status":0,"value":null}
chrome_1        | 14:51:48.055 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2ce8ae14
cTraceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 975, in up
  File "compose\cli\log_printer.py", line 105, in run
  File "compose\cli\log_printer.py", line 109, in write
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose

**Comment by ShoGinn** [comment]
Thats an odd error, its erring out for your docker-compose.

Are you using my pull or kathawala

**Comment by Brenex** [comment]
I was using yours because I don't think kathawala has docker setup anyways?

**Comment by ShoGinn** [comment]
I’ll look at each line and try and figure it out. But it doesn’t make sense. Is it consistent?

**Comment by ShoGinn** [comment]
pull the latest version and let me know

**Comment by Brenex** [comment]
I'm running the new version. A question I have is, if the searches have already been completed for the day, why does it redo them? Doesn't it read that all of the points have been accumulated for the day?

**Comment by Brenex** [comment]
with the new version it's not running it searches it seems 

[output - Copy.txt](https://github.com/ShoGinn/RewardsBot/files/1629533/output.-.Copy.txt)

**Comment by Brenex** [comment]
I think the IOerror issue was because if I ran the docker-compose up command again it output the entire contents of the running docker to the powershell window and sometimes it encountered an IOerror. I realize I need to Ctrl+C the previous instance to start a new instance using docker-compose up
