### ISSUE TITLE
Not finding rewardsbot.py

### ISSUE THREAD

**Issue by Brenex** [ShoGinn/RewardsBot#7]
this is the output when trying to run the script. For some reason it is not finding rewardsbot.py which is very strange

[output.-.Copy.txt](https://github.com/ShoGinn/RewardsBot/files/1629539/output.-.Copy.txt)

**Comment by ShoGinn** [comment]
I changed the docker file to just put things into root ;) sorry reference the new docker-compose

**Comment by Brenex** [comment]
I still get the following error with the newest version:

rewardsbot_1    | python: can't open file 'rewardsbot.py': [Errno 2] No such file or directory

**Comment by ShoGinn** [comment]
do docker-compose up -d build

**Comment by Brenex** [comment]
PS C:\Users\Danny\Downloads\RewardsBot> docker-compose up -d build
ERROR: No such service: build

**Comment by ShoGinn** [comment]
That’s my fault. Docker-compose build

**Comment by Brenex** [comment]
Thanks, got it working again!

**Comment by Brenex** [comment]
Is there a way to monitor the output in the window? I was using "docker-compose up" but it errors out.

[output1.txt](https://github.com/ShoGinn/RewardsBot/files/1629753/output1.txt)
